### ISSUE TITLE
Explain better the last example in chapter 4 - Taking Stock

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#14]
A beginner will need more guidance to fully understand the example. The notYetBorn() function should be covered by tests. The explanation of the "precision" expression should help the reader locate in the code.

**Comment by markusvoelter** [comment]
> The notYetBorn() function should be covered by tests.
done.

> The explanation of the "precision" expression should help the reader locate in the code.
done.

> A beginner will need more guidance to fully understand the example. 

what else beyond the two specific changes above should be explained?
Don't the inline comments do enough?

**Comment by vaclav** [comment]
Yes, no further changes needed.
