### ISSUE TITLE
Type-system error in chapter 5 - riskFactorForperson()

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#16]
Also 'P' in the function name should be upper case

**Comment by vaclav** [comment]
This is in the code (MPS project), not in text.

**Comment by markusvoelter** [comment]
<img width="393" alt="screen shot 2018-04-25 at 14 09 23" src="https://user-images.githubusercontent.com/592330/39244866-4ace089c-4892-11e8-8ce8-af69d7af5ad7.png">

Here? That is not a function, though.

**Comment by vaclav** [comment]
My bad, sorry. Yes, this is the name to fix.

**Comment by markusvoelter** [comment]
Fixed.
