### ISSUE TITLE
Suspitious colon in chapter 5

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#20]
"This is an important distinction:" - I have a mental association that colons precede some more formal definition or structured explanation or a list of options. Here it is neither - the following paragraphs go on explaining the composition and references. Thus I recommend using a full stop or an exclamation mark to finish the sentence. Possibly a title "Composition vs. referencing" could be used to separate the following paragraphs.

**Comment by markusvoelter** [comment]
Removed.
