### ISSUE TITLE
Chapter 6 - typos and suggestions for text improvements

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#27]
"As a software architect, we use a principle..." -> "As software architects, we use a principle..."
"you are now asked to "become a programmer" so you can use this DSL..." -> "you are now asked to "become a programmer" so THAT you can use this DSL..."
"As the tax expert we mentioned before, ..." -> "Us being tax experts, as we mentioned before, ...", or "As tax experts, ..."
"...that are the tax law for the particular period." -> "as specified by the tax law for the particular period."

**Comment by markusvoelter** [comment]
Fixed.
