### ISSUE TITLE
Chapter 6 - Databases and the System Boundary

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#29]
From the design point of view I'm not sure a Citizen should have taxId. This certainly is questionable, but perhaps calling it something socialSecurityId or citizenId would be better. Kids are citizens and do not pay taxes, for example. Why do they need a taxId? This may cause some confusion for the reader, since they may thing that the taxId field has some relationship with TaxCitizen.

**Comment by markusvoelter** [comment]
Replaced it with citizenID
