### ISSUE TITLE
Chapter 6 - use of function's local context

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#30]
In the Map section:
fun getPopSize(cityName: string) = cityData.findFirst(it.name == cityName).pop

If I'm not mistaken this is the first occurrence of a function reaching out to the outer context for the value of "cityName". Maybe this deserves a mention.

Additionally, maybe a little note on the purpose of the findFirst() function could be included.

Some languages use the term Dictionary for Maps. This could be mentioned.

**Comment by markusvoelter** [comment]
Fixed.
