### ISSUE TITLE
Chapter 8 - constrained types

### ISSUE THREAD

**Issue by vaclav** [markusvoelter/ProgrammingBasics#35]
type TrainType: string [where it.startsWith("ICE") || it.startsWith("RE")]

I guess this is the first time the ability to constraint types with code is mentioned. Perhaps more highlight to the feature could be used and its possible usages and limitations mentioned.

A curious question - can we have similar constraints on, let say, the "number" type? Perhaps to define a type for "all even numbers"? Why not?

**Comment by markusvoelter** [comment]
Fixed.
